export const GET_ARTICLES = "GET_ARTICLES";
export const ADD_ARTICLES = "ADD_ARTICLES";
export const DELETE_ARTICLES = "DELETE_ARTICLES";
export const ARTICLES_LOADING = "ARTICLES_LOADING";
export const SCRAPE_ARTICLES = "SCRAPE_ARTICLES";
export const SAVE_ARTICLES = "SAVE_ARTICLES";
